#!/usr/bin/env bash

set -Eeuo pipefail

project_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
default_factorio_executable="${HOME}/.local/share/Steam/steamapps/common/Factorio/bin/x64/factorio"
factorio_executable="${FACTORIO_EXECUTABLE:-${default_factorio_executable}}"
server_root="${FACTORIO_SERVER_ROOT:-${XDG_STATE_HOME:-${HOME}/.local/state}/factoria/factorio-server}"
server_settings="${FACTORIO_SERVER_SETTINGS:-${project_root}/scripts/factorio-server-settings.json}"
rcon_bind="${FACTORIO_RCON_BIND:-127.0.0.1:27015}"
server_port="${FACTORIO_SERVER_PORT:-34197}"

usage() {
    printf 'Usage: %s SAVE_FILE\n' "${0##*/}"
    printf '\nEnvironment overrides:\n'
    printf '  FACTORIO_EXECUTABLE       Factorio binary path\n'
    printf '  FACTORIO_SERVER_ROOT      Isolated server write-data directory\n'
    printf '  FACTORIO_SERVER_SETTINGS  Server settings JSON; auto_pause must be false\n'
    printf '  FACTORIO_RCON_BIND        RCON address and port (default: 127.0.0.1:27015)\n'
    printf '  FACTORIO_RCON_PASSWORD    RCON password; prompted when omitted in a terminal\n'
    printf '  FACTORIO_SERVER_PORT      Multiplayer port (default: 34197)\n'
}

if [[ ${1:-} == "-h" || ${1:-} == "--help" ]]; then
    usage
    exit 0
fi
if [[ $# -ne 1 ]]; then
    usage >&2
    exit 2
fi

save_file="$1"
if [[ ! -f ${save_file} ]]; then
    printf 'Save file does not exist: %s\n' "${save_file}" >&2
    exit 1
fi
save_file="$(realpath -e -- "${save_file}")"
if [[ ! -x ${factorio_executable} ]]; then
    printf 'Factorio executable is unavailable: %s\n' "${factorio_executable}" >&2
    printf 'Set FACTORIO_EXECUTABLE to the correct binary path.\n' >&2
    exit 1
fi
if [[ ! -f ${server_settings} ]]; then
    printf 'Server settings file does not exist: %s\n' "${server_settings}" >&2
    exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
    printf 'jq is required to validate the server settings.\n' >&2
    exit 1
fi
if ! jq -e '.auto_pause == false' "${server_settings}" >/dev/null; then
    printf 'Server settings must contain "auto_pause": false: %s\n' "${server_settings}" >&2
    exit 1
fi

rcon_password="${FACTORIO_RCON_PASSWORD:-}"
if [[ -z ${rcon_password} ]]; then
    if [[ ! -t 0 ]]; then
        printf 'Set FACTORIO_RCON_PASSWORD for non-interactive startup.\n' >&2
        exit 1
    fi
    read -r -s -p 'Factorio RCON password: ' rcon_password
    printf '\n'
fi
if [[ -z ${rcon_password} ]]; then
    printf 'The RCON password cannot be empty.\n' >&2
    exit 1
fi

mkdir -p -- "${server_root}"
server_root="$(cd -- "${server_root}" && pwd)"

config_directory="${server_root}/config"
mod_directory="${server_root}/mods"
log_directory="${server_root}/logs"
server_config="${config_directory}/config.ini"
bridge_source="${project_root}/factorio-mod/factoria-bridge_0.1.0"
bridge_target="${mod_directory}/factoria-bridge_0.1.0"

mkdir -p -- "${config_directory}" "${mod_directory}" "${log_directory}"

# A separate write-data directory gives the server its own .lock, saves, logs,
# and mod metadata, so the graphical client can keep using ~/.factorio.
printf '%s\n' \
    '; Generated by scripts/start-factorio-server.sh.' \
    '[path]' \
    'read-data=__PATH__system-read-data__' \
    "write-data=${server_root}" \
    '' \
    '[other]' \
    'enable-new-mods=true' \
    > "${server_config}"

if [[ ! -d ${bridge_source} ]]; then
    printf 'Bundled FactorIA Bridge mod is unavailable: %s\n' "${bridge_source}" >&2
    exit 1
fi
if [[ ! -e ${bridge_target} && ! -L ${bridge_target} ]]; then
    ln -s -- "${bridge_source}" "${bridge_target}"
fi

printf 'Starting Factorio headless server\n'
printf '  Save:       %s\n' "${save_file}"
printf '  Write data: %s\n' "${server_root}"
printf '  RCON:       %s\n' "${rcon_bind}"

exec "${factorio_executable}" \
    --config "${server_config}" \
    --mod-directory "${mod_directory}" \
    --start-server "${save_file}" \
    --server-settings "${server_settings}" \
    --port "${server_port}" \
    --rcon-bind "${rcon_bind}" \
    --rcon-password "${rcon_password}" \
    --console-log "${log_directory}/factorio-server.log"
